#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define RACQUET_WIDTH 100
#define RACQUET_HEIGHT 10
#define BALL_SIDE 10
#define WINDOW_HEIGHT 480
#define WINDOW_WIDTH 640
#define BRICK_WIDTH (WINDOW_WIDTH-20*2)/20
#define BRICK_HEIGHT (WINDOW_HEIGHT-20*2-330)/10

#endif // DEFINES_H_INCLUDED
